from collections.abc import Callable

from mcp_adf.tools import (
    data_flows,
    datasets,
    global_parameters,
    integration_runtimes,
    linked_services,
    pipelines,
    triggers,
)

# Single source of truth for the ADF tool registry, assembled from each resource-type
# module. Imported by server.py (stdio MCP path).
TOOL_REGISTRY: dict[str, Callable[..., dict]] = {
    "list_pipelines": pipelines.list_pipelines,
    "create_pipeline": pipelines.create_pipeline,
    "get_activity_run_error": pipelines.get_activity_run_error,
    "list_activity_runs": pipelines.list_activity_runs,
    "get_activity_run_io": pipelines.get_activity_run_io,
    "get_pipeline_run_status": pipelines.get_pipeline_run_status,
    "get_pipeline_run_history": pipelines.get_pipeline_run_history,
    "list_pipeline_runs": pipelines.list_pipeline_runs,
    "get_activity_run_history": pipelines.get_activity_run_history,
    "get_pipeline_definition": pipelines.get_pipeline_definition,
    "get_linked_service": linked_services.get_linked_service,
    "rerun_pipeline": pipelines.rerun_pipeline,
    "get_integration_runtime_status": integration_runtimes.get_integration_runtime_status,
    "start_integration_runtime": integration_runtimes.start_integration_runtime,
    "get_trigger": triggers.get_trigger,
    "start_trigger": triggers.start_trigger,
    "get_pipeline_definition_raw": pipelines.get_pipeline_definition_raw,
    "update_pipeline_definition": pipelines.update_pipeline_definition,
    "list_pipeline_snapshots": pipelines.list_pipeline_snapshots,
    "rollback_pipeline_definition": pipelines.rollback_pipeline_definition,
    "back_pipeline_definition": pipelines.back_pipeline_definition,
    "forward_pipeline_definition": pipelines.forward_pipeline_definition,
    "stop_trigger": triggers.stop_trigger,
    "list_triggers": triggers.list_triggers,
    "get_trigger_run_history": triggers.get_trigger_run_history,
    "rerun_trigger_run": triggers.rerun_trigger_run,
    "cancel_trigger_run": triggers.cancel_trigger_run,
    "list_linked_services": linked_services.list_linked_services,
    "get_linked_service_definition_raw": linked_services.get_linked_service_definition_raw,
    "update_linked_service_definition": linked_services.update_linked_service_definition,
    "list_linked_service_snapshots": linked_services.list_linked_service_snapshots,
    "rollback_linked_service_definition": linked_services.rollback_linked_service_definition,
    "back_linked_service_definition": linked_services.back_linked_service_definition,
    "forward_linked_service_definition": linked_services.forward_linked_service_definition,
    "cancel_pipeline_run": pipelines.cancel_pipeline_run,
    "list_datasets": datasets.list_datasets,
    "get_dataset_definition_raw": datasets.get_dataset_definition_raw,
    "update_dataset_definition": datasets.update_dataset_definition,
    "list_dataset_snapshots": datasets.list_dataset_snapshots,
    "rollback_dataset_definition": datasets.rollback_dataset_definition,
    "back_dataset_definition": datasets.back_dataset_definition,
    "forward_dataset_definition": datasets.forward_dataset_definition,
    "get_data_flow_definition": data_flows.get_data_flow_definition,
    "update_data_flow_definition": data_flows.update_data_flow_definition,
    "list_data_flow_snapshots": data_flows.list_data_flow_snapshots,
    "rollback_data_flow_definition": data_flows.rollback_data_flow_definition,
    "back_data_flow_definition": data_flows.back_data_flow_definition,
    "forward_data_flow_definition": data_flows.forward_data_flow_definition,
    "list_global_parameters": global_parameters.list_global_parameters,
    "get_global_parameter_definition_raw": global_parameters.get_global_parameter_definition_raw,
    "update_global_parameter_definition": global_parameters.update_global_parameter_definition,
    "list_global_parameter_snapshots": global_parameters.list_global_parameter_snapshots,
    "rollback_global_parameter_definition": global_parameters.rollback_global_parameter_definition,
    "back_global_parameter_definition": global_parameters.back_global_parameter_definition,
    "forward_global_parameter_definition": global_parameters.forward_global_parameter_definition,
}
